# Generated by Django 3.0.8 on 2020-08-01 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('text', models.TextField()),
            ],
        ),
    ]
